version: '3.3'

services:

  linux1:
    build: .
    hostname: gdsc-mini-ctf
    ports:
      - '40100:22'

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
